name: Storybook
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Get Package Version 🏷
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Install and Build 🔧
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          target-folder: .
          branch: gh-pages
          clean: true
          force: true
          tag: ${{ steps.package-version.outputs.current-version}}
